version: '3.8'
services:
  php:
    image: markoshust/magento-php:8.2-fpm
    container_name: magento2-php
    volumes:
      - ./src:/var/www/html
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
    working_dir: /var/www/html
    depends_on:
      - db
      - opensearch
  nginx:
    image: nginx:latest
    container_name: magento2-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  db:
    image: mysql:8.0
    container_name: magento2-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - dbdata:/var/lib/mysql
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: magento2-opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - opensearchdata:/usr/share/opensearch/data
volumes:
  dbdata:
  opensearchdata:
